name: CI
on: [push]
jobs:
  test_build_run_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run : |
          pip install pytest
          pytest
      - name: build docker image
        run :
        docker build -t valid_password .
      - name: run docker image
        run:
          docker run valid_password